apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sc-app
  template:
    metadata:
      labels:
        app: sc-app
    spec:
      containers:
      - image: alpine
        name: secret-container
        command: ['sh', '-c', 'while true; do echo my password: $PASS; sleep 1; done']
        env:
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password