apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-server
  labels:
    app: my-web-server
spec:
  selector:
    matchLabels:
      app: my-web-server
  template:
    metadata:
      labels:
        app: my-web-server
    spec:
      volumes:
        - name: mypv
          persistentVolumeClaim:
            claimName: mypvc
      containers:
        - name: web-server
          image: nginx
          ports:
            - containerPort: 80
              name: "http-server"
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: mypv